export const SET_TO_ADDRESS_SEARCH = 'SET_TO_ADDRESS_SEARCH';
export const SET_FROM_ADDRESS_SEARCH = 'SET_FROM_ADDRESS_SEARCH';
export const SET_ADDRESS_SUGGESTIONS = 'SET_ADDRESS_SUGGESTIONS';
export const RESET_ADDRESS_SUGGESTIONS = 'RESET_ADDRESS_SUGGESTIONS';
export const SET_ADDRESS_SELECTION = 'SET_ADDRESS_SELECTION';
