export const SET_TO_ADDRESS_SEARCH = 'SET_TO_ADDRESS_SEARCH';
export const SET_FROM_ADDRESS_SEARCH = 'SET_FROM_ADDRESS_SEARCH';
export const SET_ADDRESS_SUGGESTIONS = 'SET_ADDRESS_SUGGESTIONS';
export const RESET_ADDRESS_SUGGESTIONS = 'RESET_ADDRESS_SUGGESTIONS';
export const SET_TO_ADDRESS_SELECTION = 'SET_TO_ADDRESS_SELECTION';
export const SET_FROM_ADDRESS_SELECTION = 'SET_FROM_ADDRESS_SELECTION';
export const SET_FOCUSED_SEARCH_FIELD = 'SET_FOCUSED_SEARCH_FIELD';

export const SET_FROM_STATION_OPTIONS = 'SET_FROM_STATION_OPTIONS';
export const SET_TO_STATION_OPTIONS = 'SET_TO_STATION_OPTIONS';
export const SET_SELECTED_FROM_STATION = 'SET_SELECTED_FROM_STATION';
export const SET_SELECTED_TO_STATION = 'SET_SELECTED_TO_STATION';
